### ISSUE TITLE
cant use HTTPS

### ISSUE THREAD

**Issue by istek** [sethbrasile/ghost-cloudinary-store#10]
i have followed install construction and edited config.js file,
added `secure: true` .

then i restart ghost, it doesn't work!

**Comment by sethbrasile** [comment]
@istek https://github.com/sethbrasile/ghost-cloudinary-store/blob/master/index.js#L20

`ghost-cloudinary-store` is using the `cloudinary` package's `secure_url` when `secure` is set to `true`, so that URL should be coming straight from Cloudinary.

My guess is that your config is not set properly. Possibly setting in the `production` env, but then you're using `development` or something like that?

Could you paste your config?

Another thing to check, I haven't checked out the new versions of the `cloudinary` package from npm. Maybe make sure that the one that is installed is the one specified in `ghost-cloudinary-store`'s `package.json`?

**Comment by istek** [comment]
hi. i found i haven't set config.js properly.right now it's working.really thanks.

**Comment by sethbrasile** [comment]
👍
