### ISSUE TITLE
Cannot read property 'image' of undefined

### ISSUE THREAD

**Issue by carloscuesta** [sethbrasile/ghost-cloudinary-store#22]
Hello!

While using the last version of Ghost (1.10.0) with `ghost-cloudinary-store` if you try to upload an image this error is thrown:

![screen shot 2017-09-30 at 22 23 08](https://user-images.githubusercontent.com/7629661/31049180-0fe10326-a62e-11e7-80da-16df3646ac2a.png)

**Comment by mmornati** [comment]
I just tested it after the update to the 1.10.0 version and all is working good to me.
I also updated the plugin to the latest version (on the NPM... before was updated on github but not uploaded in the npm repo).

Checking the line where the error is thrown, I think you have anything incorrect in your configuration file:
`var cloudinaryImageSettings = this.config.configuration.image;`
It seems your "configuration" is empty.
Here you are the configuration I've on my blog:
```json
"storage": {
    "active": "cloudinary-store",
    "cloudinary-store": {
      "configuration": {
        "image": {
          "quality": "auto:good",
          "secure": "true"
        },
        "file": {
          "use_filename": "true",
          "unique_filename": "false",
          "phash": "true",
          "overwrite": "false",
          "invalidate": "true"
        }
      }
    }
  }
```

**Comment by carloscuesta** [comment]
I've configured the module as the docs says: 

On my `config.production.json` the storage object is set to:

```
"storage": {
    "active": "ghost-cloudinary-store",
    "ghost-cloudinary-store": {
        "cloud_name": "name",
        "api_key": "key",
        "api_secret": "apiSecret"
    }
}
```

Then inside of `/content/adapters/storage/ghost-cloudinary-store` I've installed the module.

 Maybe I'm missing something but it's not working for me

**Comment by mmornati** [comment]
That part of the documentation should be updated... Just check the second one.
I will update it (even if this repo is not actually the official one... as the reference on the ghost documentation is on another one).

**Comment by carloscuesta** [comment]
What's the official repo then? The one referenced in the docs it's your fork, and has the exact same documentation as this one. If this is not supported anymore, add a deprecation notice at the README

**Comment by mmornati** [comment]
Yes. I had it before but I think a PR removed it in some way.
Actually it is my fork which referenced 'cause before no-one was working on
this one and we had problems contacting Seth.
As I said I'm updating both 2 repos with the same code (even if sometimes
it can be not synchronized automatically at the same moment).

Anyway, did you fixed your problem with the configuration update?



On Oct 1, 2017 14:51, "Carlos Cuesta" <notifications@github.com> wrote:

What's the official repo then? The one referenced in the docs it's your
fork, and has the exact same documentation as this one. If this is not
supported anymore, add a deprecation notice at the README

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/sethbrasile/ghost-cloudinary-store/issues/22#issuecomment-333374553>,
or mute the thread

**Comment by carloscuesta** [comment]
Yes! Everything is working now.

I would suggest you to only maintain one repo, will be easier for you!

**Comment by mmornati** [comment]
Yes I'm thinking to the same thing. Don't know what is the best way to
communicate it but I will do.
Maybe just removing the Readme here (and files?) and putting, as you
suggested, the information to redirect to the other one.
Thanks man!

**Comment by carloscuesta** [comment]
Yes! I would write a deprecation message at the top of the readme. After that you can deprecate the package on NPM to warn users when installing the package that is deprecated. More info 👇 

https://docs.npmjs.com/cli/deprecate
